server:
  port: 8084
spring:
  application:
    name: producto-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/producto_service?useSSL=false&serverTimezone=UTC
    username: rodr1alex
    password: 1234

eureka:
  client:
    service-url.defaultZone: http://localhost:8761/eureka



